language: node_js
cache:
  directories:
    - "node_modules"
    - "augmint-contracts/node_modules"
install:
    - yarn install
    - cd augmint-contracts && npm install && cd ..
before_script:
    - yarn run ganache:run > ganache.out &
    - yarn run truffle:migrate
    - yarn start  &
script:
    - yarn run cypress:runrecord
# discord webhooks hack until this is released: https://github.com/travis-ci/travis-tasks/pull/71
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success https://discordapp.com/api/webhooks/409413234337251328/lCt9WUG15qc8s0PjqijUplpVjVx1MS_8wFkcMiVxA4ZWAZdUzdY3frnKRiVZC0iY0YC5
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discordapp.com/api/webhooks/409413234337251328/lCt9WUG15qc8s0PjqijUplpVjVx1MS_8wFkcMiVxA4ZWAZdUzdY3frnKRiVZC0iY0YC5
