language: node_js
cache:
  directories:
    - "node_modules"
before_install:
    - npm install -g truffle@4.0.4
install:
    - npm install
before_script:
    - npm run ganache:run > ganache.out &
    - truffle migrate && cp build/contracts/* src/contractsBuild
    - yarn start > yarn_start.out &
script:
    - truffle test
    - cypress run --record --key 42b3c18f-e1cf-4c27-85ed-c223e420bd4a
