dist: xenial # https://docs.travis-ci.com/user/reference/xenial/
language: node_js
services:
  - docker
cache:
  directories:
    - "~/.cache" # based on: https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
install:
  - sudo apt-get install -y libgconf-2-4 # https://github.com/cypress-io/cypress/issues/1526
  - sudo apt-get install build-essential # fix for build occasionally failing with node_gyp build
  - yarn global add greenkeeper-lockfile
  - |
    if [[ $BRANCH == "greenkeeper/"* ]]; then
      echo Greenkeeper build using .yarnrc.greenkeeper; cp .yarnrc.greenkeeper .yarnrc; yarn install;
    else
      echo Normal build using .yarnrc and --frozen-lockfile option; yarn install --frozen-lockfile;
    fi
before_script:
  - greenkeeper-lockfile-update
  - yarn ganache:start > /dev/null &
  - yarn start &
  - wait-on http-get://localhost:3000 # webserver
  - wait-on tcp:localhost:8545 # ganache
script:
  - yarn test # jest tests
  - yarn cypress:run
after_script: greenkeeper-lockfile-upload
# discord webhooks hack until this is released: https://github.com/travis-ci/travis-tasks/pull/71
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
env:
  global:
    - secure: CEe2RntKnyZa89E0cx3thLcTU0AJ5TyWayO4y+4FYJ1d3nEv8IS3y5F6fZcaqO/GYCtr7xUIOoqYOPWcWIeLDo2QMBWntJU26LXezrVP90idYkv9PRpBKMDVmZaSh4kzUJMdJhenq+KVBEtn8yLRU5nwLYnFZroZuHN5KV0iHLYuqVB2zc8cX6vOOoL9fJbI9z/HfdNqMugBoNURMLmlW69AxYAOWYP78NnsljLyCc7jV/xaIRQsVAV8WkD9TQ6ejnx31kigcgXWvjE6TP7ki3P7RicP6LxPv33053hjduaqz+0nd87v3LLEV9ZOGL3JGkc3slA79MzymUphU/Mqz9dsjcR9unHynyINW13jUVrnGpWHsBxeNaTX9hiCyvIaGUQLIp6KO++QVVOSra+9J+euzzUcKrYFa/L0lxR6lrxoFAxbzcwVQE1g8WAb3t2esOFe2yNuoIZz5UMiCnS3u6TE3Tm7Vt9OFEDu5TLlc16Nw7QUFOHNr+q+gzBSDGeypfVIQIwIhL5DdKdfN+TLZIuuSISgocs1dql+xSRjXSQN04AjaSX0GyWZDgETb491UVoLaFtHb3UIHBTAfmF4npDUjl0Z0FpBk4AXZADCWxRvmYiRTi2xvviTtAqr3hnww96DJe5uP92bWtD/3g0M//jzMWSvhPxdEfWxmsjC+iY=
    # DISCORD_WEBHOOK_URL:
    - secure: JgYtX+lP4IVTpaXgjBphTY1/Oy+p68N8VPc7825MOmsVglSUK+tk4a6vFugG/dvrpG+z9KxtCWPnwS1dIy7Y0o3wab8CJR3f2SgWIxF1jUBxqk2/MEnrfAldjU8wSgW6jWFPuUjDDtcAFPonS6VU8KtwQad6U6nGIvaCuu2lwx2ARcLC+yiRFiZeyp83bUqHNSt+4sH6s1iLklxqoBkMOD0PgkEFG/axKP94W/vCloWVVnMcvB+iNYIIEQhTXDfeXayiqlVEUhUxIt2ZLSa30vCOMnQdgzTliX7xyIAN2gmn/O1Vx3jM3BwiTdY2mkkJVtc1EOLwaKXDLUACWAcxtd9MiyZxF7bveD97d+I701azNwXr7C8H1tcqzXyHGO/CIa9IMvfJcTF2XiZQv5mrOujxpLaGCX8FzPJpR+AUu6EtnHPpULpsZA+sANrJxq2E3xR4o0ciYtuSHsWlaDgTRUFMByqa6vCuK365P3EDezOU0EfcrJX1RWvZWHD7/TBrKitEP6YsXFJKMOZ5kldaKo07as1l4ZNJDfFCSaiKhzZCHOWSE/othYLhxu++ZkNaO1u5Du7ZJ/IClomsoRG5UeEca9YU4rim7sVCKMbJ/i5l93WwcxfSFrbbo5Y8RlwGNhm79t3DcONtVviRYaX0uJFaMGyQyDl+cnbHFhMLOD4=
