language: node_js
cache:
  directories:
    - "node_modules"
before_install:
    - npm install -g truffle@4.0.4
install:
    - npm install
before_script:
    - npm run ganache:run &
build:
    - truffle migrate && cp builds/contracts/* src/
script:
    - yarn start &
    - truffle test
    - npm run cypress:run
