language: node_js
before_install:
    - npm install -g truffle@4.0.4
install:
    - npm install
before_script:
    - npm run ganache:runmigrate
build:
    - truffle migrate && cp builds/contracts/* src/
test:
    - truffle test
    - npm run cypress:run
cache:
  directories:
    - "node_modules"
